# Generated by Django 5.0.6 on 2024-09-06 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_user_email_alter_user_passage_id"),
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contato_corretor", models.IntegerField(blank=True, max_length=11, null=True, unique=True)),
                ("disponibilidade", models.BooleanField(default=True)),
                ("definicao_data", models.DateTimeField()),
                ("confirmacao", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Comodidade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("estacionamento", models.CharField(blank=True, max_length=255, null=True)),
                ("acessibilidade", models.CharField(blank=True, max_length=255, null=True)),
                ("seguranca", models.CharField(blank=True, max_length=255, null=True)),
                ("tecnologia", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Imoveis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.IntegerField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=5)),
                ("localizacao", models.CharField(blank=True, max_length=255, null=True)),
                ("metragem", models.IntegerField(blank=True, null=True)),
                ("quantidade_quarto", models.IntegerField(default=1)),
                ("quantidade_banheiro", models.IntegerField(default=1)),
                ("quantidade_suite", models.IntegerField(default=1)),
                ("status", models.BooleanField(default=True)),
                (
                    "foto",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="uploader.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imoveis",
                "verbose_name_plural": "Imoveis",
            },
        ),
    ]
