# Generated by Django 5.0.6 on 2024-09-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_agendamento_comodidade_imoveis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamento",
            name="contato_corretor",
            field=models.BigIntegerField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
