# Generated by Django 5.0.6 on 2024-09-06 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_categoria_tipousuario_alter_imoveis_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="imoveis",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.imoveis"
            ),
        ),
        migrations.AddField(
            model_name="comodidade",
            name="imoveis",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.imoveis"
            ),
        ),
    ]
