# Generated by Django 5.0.6 on 2024-09-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_imoveis_foto_imoveis_foto"),
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tipo_usuario",
        ),
        migrations.AlterField(
            model_name="imoveis",
            name="foto",
            field=models.ManyToManyField(blank=True, default=None, to="uploader.image"),
        ),
    ]
