# Generated by Django 5.0.6 on 2024-09-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_user_tipo_usuario_alter_imoveis_foto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TipoUsuario",
        ),
    ]
