# Generated by Django 5.0.6 on 2024-12-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_imoveis_foto_imoveis_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="imoveis",
            name="nome",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
