# Generated by Django 5.0.6 on 2024-12-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_imoveis_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imoveis",
            name="metragem",
            field=models.IntegerField(),
        ),
    ]
